// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcsjleznjyuxbysrspdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjc2psZXpuanl1eGJ5c3JzcGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTc0ODUsImV4cCI6MjA2OTg3MzQ4NX0.x0r7JeYnCUerccMOUuu4Kgj1QHGYNlUt73i_fCMl47E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});